### ISSUE TITLE
Site //TODO

### ISSUE THREAD

**Issue by Moo64c** [Moo64c/fb-safety#1]
To do list:
### Design
- [ ]  Event display.
- [ ]  Top bar login / logout
### Functionality
- [ ]  Parent child selection.
- [ ]  Allow some options for the child.
- [ ]  Enable emailing (Shmuel computer only?)
### DB
- [ ]  Lock DB.
### (after locking only)
- [ ]  create some basic migration for demo.
